name: Playwright API Tests

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    name: Playwright API + Allure
    needs: lint
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      URL_TRANSFER_API: ${{ secrets.URL_TRANSFER_API }}
      API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browser (Chromium only)
        run: npx playwright install chromium

      - name: Run API tests
        run: npm run test:api
        continue-on-error: true

      - name: Install Allure CLI
        if: ${{ !cancelled() }}
        run: npm install -g allure-commandline

      - name: Generate Allure report
        if: ${{ !cancelled() }}
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-api-report
          path: allure-report/
          retention-days: 30
